### ISSUE TITLE
The wiki does not work

### ISSUE THREAD

**Issue by crispgm** [stv0g/libqt-omd#1]
Very interested in the Olympus OM-D Wi-Fi protocol
Please fix the wiki or provide me the documentation if possible

Best regards.

**Comment by stv0g** [comment]
Hi David,

I had a little security breach on my server a few weeks ago.
I am still recovering from this..

I will notify you here as soon as the wiki is back!

Cheers,

Steffen

**Comment by crispgm** [comment]
Thanks, Steffen.

**Comment by stv0g** [comment]
Sorry for the delay, It will take another few weeks to get the wiki up again.
Are you looking for something in particular?

**Comment by crispgm** [comment]
Thanks for your efforts.
I am just curious about the hacks on Olympus camera and may do something interesting for my own one.
Please take your time and my requirement is not urgent. :)

**Comment by spcampbell** [comment]
Very interested in the wiki information as well. Thank you for all your work and don't hesitate to ask for help.

**Comment by crispgm** [comment]
@stv0g hey guy. I have almost understood the Wi-Fi commands by reading your C++ codes.
The issue might be closed.
And i will write a blog about the protocol recently.
It is appreciated if you review the blog for me.

cheers

**Comment by stv0g** [comment]
Sure, just send me a link to stv0g@0l.de

Cheers

**Comment by stv0g** [comment]
The wiki is now reachable again: https://dev.0l.de/wiki/projects/omd/start
