### ISSUE TITLE
Wiki not reachable

### ISSUE THREAD

**Issue by MartinSoto** [stv0g/libqt-omd#3]
Hi, I'd really love to see the Image Share protocol information you collected, but the document doesn't seem to be reachable anymore. Any chances of uploading it to GitHub or making it available otherwise?

**Comment by stv0g** [comment]
Hi Martin,

The wiki should be up again.. I had some DNS issues on my side.

**Comment by MartinSoto** [comment]
Hi Steffen, unfortunately the link pointing to the Wiki from this project's Readme, https://dev.0l.de/wiki/projects/omd/, continues to be broken. The page says "This topic does not exist yet". Am I missing something?

**Comment by stv0g** [comment]
Mh :-(

The DokuWiki has/had some problems with caching.
I purged the cache, now it is working (at least for me)

**Comment by MartinSoto** [comment]
Just tried to access the link from two different devices and attempted a forced refresh (Shift + refresh) in one of them, all to no avail. Can it be related to you being logged in to the wiki? I also tried registering to the Wiki and it tells me that it couldn't send the password email and that I should contact the administrator... :-P

**Comment by stv0g** [comment]
Can you try again?

- I disabled some plugins which seem not to be supported by PHP 7
- I checked with beeing logged in and out.
- You can try appending `&purge=true` to the URL to get a freshly rendered version of the page.

**Comment by MartinSoto** [comment]
Hi Steffen, still no success. For me, it all looks the same: the page looks empty, and I can't register/log in because of an error sending the password email. Are you sure we're looking at the same URL?

By the way, any chances of you uploading the protocol information to GitHub?

**Comment by stv0g** [comment]
Damn :( I would like to keep my notes at the wiki for now.

One last try. I figured out that due to my upgrade to PHP 7.0, some functions where missing.
After installing php-7.0-xml, the page now renders correclty.

**Comment by MartinSoto** [comment]
Hallelujah brother! I finally managed to get to the page! I searched the wiki for OMD and got working results. The URL in the README is still broken, though, it should read https://dev.0l.de/projects/omd/start, that is, without the "wiki" prefix.

Thanks a lot for the help with this issue and for collecting the OMD protocol info; all very appreciated!
